services:
  autogluon-ui:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=./mlruns
    command: streamlit run app.py

  mlflow-ui:
    image: ghcr.io/mlflow/mlflow:v2.11.1
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri /mlruns
